Feat custom enumerable methods
trekab/enumerable-methods pull request #1
Opened 2019-11-20 15:41 UTC by trekab

This PR shows my endeavors to create some custom enumerable methods as required by the odin project. Project 2(https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks).

2019-11-20 18:30 UTC, ebukaume requested changes
## Changes required! :stop_sign: 

Hi @trekab  :wave: 

Nice job so far. Some of the tests are passing but there are a few you need to fix. Kindly see below for more details.

**Kindly submit another code review after fixing these issues**. _You can always run your own tests to make sure you got it right_ :wink: 

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-20 18:30 UTC, ebukaume commented on enumerable_methods.rb
> +  end
You seem to have swapped the order of the block variables here.  :point_right:  `each with index` :wink: 

`[2, 4, 6].each_with_index { |num, index| puts "#{num} -> #{index}" }` should output:

```
2 -> 0
4 -> 1
6 -> 2
```

2019-11-20 18:30 UTC, ebukaume commented on enumerable_methods.rb
> +  end
What happens when a block is not given?

`[1, true, :sym].my_all?` ==  `[1, true, :sym].all?` == `true`

`[1, 2, 3].my_all?(Integer)` ==  `[1, 2, 3].all?(Integer)` == `true`

However, you method throws an error:

> ArgumentError:
       wrong number of arguments (given 1, expected 0)

I advise you to test all your method against the once ruby provide.

2019-11-20 18:30 UTC, ebukaume commented on enumerable_methods.rb
> +  end
What happens when no block is given? From your implementation, you always return `false`. So if I run `[nil, true].my_any?` I would get `false`. You need to fix this.

Consider having another execution path for when a block is not given.

Also, when I run `[nil, true, 2].my_any?(Integer)`, I get the error below:

> ArgumentError:
>        wrong number of arguments (given 1, expected 0)

2019-11-20 18:30 UTC, ebukaume commented on enumerable_methods.rb
> +  end
Same problem as with `#my_all?`

2019-11-20 18:30 UTC, ebukaume commented on enumerable_methods.rb
> +  end
`[1, 2, 3].my_inject(:+)` throws an error.

>       ArgumentError:
>         wrong number of arguments (given 1, expected 0)

Also, [10, 2, 3].my_inject(&:+) returns 16 (it seems to always be 1 more than the correct answer).

2019-11-20 21:10 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello @trekab   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

- Please check my comments below and fix the mentioned errors, check [this](https://ruby-doc.org/core-2.6.5/Enumerable.html) for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-20 21:10 UTC, Redvanisation commented on enumerable_methods.rb
> +  end
my_all? method still gives an error while running the code below:

`[1, 2, 3].my_all?(Integer) == [1, 2, 3].all?(Integer) == true`

> ArgumentError:
> wrong number of arguments (given 1, expected 0)

2019-11-20 21:10 UTC, Redvanisation commented on enumerable_methods.rb
> +  end
my_any? is still returning the error below when we run the following code:  `[nil, true, 2].my_any?(Integer)`

> ArgumentError:
> wrong number of arguments (given 1, expected 0)

2019-11-20 21:10 UTC, Redvanisation commented on enumerable_methods.rb
> +end
When running my_inject with this code it gives the following error:

`[1, 2, 3].my_inject(:+)`

>       Failure/Error: expect(array.my_inject(:+)).to eq array.inject(:+)
>       
>       LocalJumpError:
>         no block given (yield)

2019-12-03 17:31 UTC, trekab commented
I am done with the required changes!!!

2019-12-03 18:00 UTC, imhta requested changes
# Require Changes 🛑 

### Hello @trekab, 👋 `my_none` and `my_any` methods are failing the test. try to fix it. kindly check the inline comment.

---
#### Don't forgot to request another code review 
---

** Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

2019-12-03 18:00 UTC, imhta commented on enumerable_methods.rb
> +  end
There are some issue with `my_any?` method
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns false if none of the s are false or nil
collection matches the pattern

2019-12-03 18:00 UTC, imhta commented on enumerable_methods.rb
> +  end
There are some issue with `my_none?` method
- when no block or argument is given returns true only if none of the collection mion is a member of such class    embers is true
- when a class is passed as an argument returns true if none of the collection is collection matches the pattern   
a member of such class
- when a Regex is passed as an argument returns true only if none of the collectioa member of such classn matches the Regex
- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the patte the collection matches the pattern

2019-12-03 18:40 UTC, imhta requested changes
# Require Changes 🛑 

### Hello @trekab, 👋  There are some methods are failing the test. try to fix it. kindly check the inline comment.

---
#### Don't forgot to request another code review 
---

** Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

2019-12-03 18:40 UTC, imhta commented on enumerable_methods.rb
> +  end
In `my_each_with_index`
- my_each_with_index calls the given block once for each element in self

2019-12-03 18:40 UTC, imhta commented on enumerable_methods.rb
> +  end
In `my_all?`
- my_all? when no block or argument is given returns true when none of the collection members are false or nil

2019-12-03 18:40 UTC, imhta commented on enumerable_methods.rb
> +  end
In `my_any?`
- my_any? when no block or argument is given returns true if at least one of the collection is not false or nil

2019-12-03 18:40 UTC, imhta commented on enumerable_methods.rb
> +  end
In `my_none?`
- my_none? when no block or argument is given returns true only if none of the collection members is true

2019-12-04 21:56 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi @trekab :wave: 

You are really doing great. I like your determination and perseverance, please keep it up. Let fix these 2 issues that are still there in your solution.
- [ ] `my_any?` returns a wrong value when a `proc` is passed.
- [ ] `[false, nil].my_any?` is expected to return `false` but I am getting `true`.

**Kindly submit another code review request after making the fixes**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-04 21:56 UTC, ebukaume commented on enumerable_methods.rb
> +  end
Consider when a `proc` is passed as the argument.

2019-12-04 22:40 UTC, ebukaume approved these changes
We are now good to go :+1:  **You can go ahead and merge this branch**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-04 22:43 UTC, trekab commented
:relaxed: :handshake:

2019-12-05 00:10 UTC, merged